server:
  port: 8308
spring:
  application:
    name: xxl-business-d
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
      config:
        server-addr: localhost:8848 #Nacos地址
        file-extension: yaml
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: ${spring.application.name}
service-url:
  xxl-business-c: http://xxl-business-c

management:
  endpoints:
    web:
      exposure:
        include: '*'