server:
  port: 8801
spring:
  application:
    name: xxl-zuul
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
zuul:
  routes: #给服务配置路由,自动配置的路由以服务名称为匹配路径
    xxl-business-a:
      path: /xxl-business-a/**
    xxl-business-b:
      path: /xxl-business-b/**
  #  ignored-services: xxl-business-a,xxl-business-b #关闭默认路由配置
  #  prefix: /proxy #给网关路由添加前缀
  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
  add-host-header: true #设置为true重定向是会添加host请求头
  # filterClassName
  PreLogFilter:
    pre:
      disable: true #控制是否启用过滤器

#用来查看Zuul中的路由信息
management:
  endpoints:
    web:
      exposure:
        include: 'routes'