server:
  port: 8001 #指定运行端口
spring:
  application:
    name: xxl-register-center-eureka #指定服务名称
#  security: #配置SpringSecurity登录用户名和密码
#    user:
#      name: xxl
#      password: 123456
eureka:
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
  server:
    enable-self-preservation: false #关闭保护模式